### ISSUE TITLE
Error Too many SOQL queries: 101 

### ISSUE THREAD

**Issue by Dothack41** [ForceDotComLabs/QuotaEdit#39] opened 2016-03-07 17:11 UTC
When I try to open EditQuotas I get a error 
"EditQuotas:Too many SOQL queries: 101 
An unexpected error has occurred. Your solution provider has been notified. (EditQuotas)"

What could be cuasing the problem

**Comment by alonkama** [comment] 2016-03-07 17:12
Thanks for bringing it up. It's a duplicate of #10 . I hope to upload a fix later today.

**Closed by alonkama** 2016-03-07 17:12 UTC
