### ISSUE TITLE
EditQuotas page fails since auto-upgrade to version 1.7

### ISSUE THREAD

**Issue by JmeG** [ForceDotComLabs/QuotaEdit#40] opened 2016-03-07 17:46 UTC
EditQuotas:Too many SOQL queries: 101 
An unexpected error has occurred. Your solution provider has been notified. (EditQuotas)

**Comment by alonkama** [comment] 2016-03-07 17:51
Thanks for bringing it up. It's a duplicate of #10 . I hope to have a fix later today.

**Closed by alonkama** 2016-03-07 17:51 UTC
